// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ewm/system_info.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SystemInfo struct {
	ProofSessionId     uint64 `protobuf:"varint,1,opt,name=proofSessionId,proto3" json:"proofSessionId,omitempty"`
	ChainRoleId        uint64 `protobuf:"varint,2,opt,name=chainRoleId,proto3" json:"chainRoleId,omitempty"`
	FifoHeadIndex      string `protobuf:"bytes,3,opt,name=fifoHeadIndex,proto3" json:"fifoHeadIndex,omitempty"`
	FifoTailIndex      string `protobuf:"bytes,4,opt,name=fifoTailIndex,proto3" json:"fifoTailIndex,omitempty"`
	ChainConfigId      uint64 `protobuf:"varint,5,opt,name=chainConfigId,proto3" json:"chainConfigId,omitempty"`
	StoredSessionCount uint64 `protobuf:"varint,6,opt,name=storedSessionCount,proto3" json:"storedSessionCount,omitempty"`
}

func (m *SystemInfo) Reset()         { *m = SystemInfo{} }
func (m *SystemInfo) String() string { return proto.CompactTextString(m) }
func (*SystemInfo) ProtoMessage()    {}
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dce67b0ae92c492, []int{0}
}
func (m *SystemInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SystemInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SystemInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SystemInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemInfo.Merge(m, src)
}
func (m *SystemInfo) XXX_Size() int {
	return m.Size()
}
func (m *SystemInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SystemInfo proto.InternalMessageInfo

func (m *SystemInfo) GetProofSessionId() uint64 {
	if m != nil {
		return m.ProofSessionId
	}
	return 0
}

func (m *SystemInfo) GetChainRoleId() uint64 {
	if m != nil {
		return m.ChainRoleId
	}
	return 0
}

func (m *SystemInfo) GetFifoHeadIndex() string {
	if m != nil {
		return m.FifoHeadIndex
	}
	return ""
}

func (m *SystemInfo) GetFifoTailIndex() string {
	if m != nil {
		return m.FifoTailIndex
	}
	return ""
}

func (m *SystemInfo) GetChainConfigId() uint64 {
	if m != nil {
		return m.ChainConfigId
	}
	return 0
}

func (m *SystemInfo) GetStoredSessionCount() uint64 {
	if m != nil {
		return m.StoredSessionCount
	}
	return 0
}

func init() {
	proto.RegisterType((*SystemInfo)(nil), "covalenthq.ewm.ewm.SystemInfo")
}

func init() { proto.RegisterFile("ewm/system_info.proto", fileDescriptor_0dce67b0ae92c492) }

var fileDescriptor_0dce67b0ae92c492 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3f, 0x4e, 0xc3, 0x30,
	0x14, 0x87, 0x6b, 0x28, 0x95, 0x30, 0x82, 0xc1, 0x93, 0x61, 0xb0, 0x22, 0x84, 0x50, 0x17, 0x92,
	0x81, 0x1b, 0xd0, 0x01, 0xbc, 0xa6, 0x4c, 0x2c, 0x28, 0x8d, 0x9f, 0x1b, 0x4b, 0xa9, 0x5f, 0x88,
	0xdd, 0xaa, 0xbd, 0x05, 0xc7, 0x62, 0xec, 0xc8, 0x88, 0x92, 0x4b, 0x30, 0x22, 0x4c, 0xd3, 0x52,
	0xc4, 0x64, 0xeb, 0x7b, 0xdf, 0xfb, 0xa3, 0x1f, 0x3d, 0xcf, 0x71, 0x01, 0x16, 0x7c, 0xe2, 0x56,
	0xce, 0xc3, 0xec, 0xd9, 0x58, 0x8d, 0x71, 0x55, 0xa3, 0x47, 0x76, 0x91, 0xe3, 0x22, 0x2b, 0xc1,
	0xfa, 0xe2, 0x25, 0xde, 0x58, 0xdd, 0x7b, 0xf9, 0x49, 0x28, 0x1d, 0x87, 0x0e, 0x69, 0x35, 0xb2,
	0x6b, 0x7a, 0x56, 0xd5, 0x88, 0x7a, 0x0c, 0xce, 0x19, 0xb4, 0x52, 0x71, 0x12, 0x91, 0x61, 0x3f,
	0xfd, 0x43, 0x59, 0x44, 0x4f, 0xf2, 0x22, 0x33, 0x36, 0xc5, 0x12, 0xa4, 0xe2, 0x07, 0x41, 0xfa,
	0x8d, 0xd8, 0x15, 0x3d, 0xd5, 0x46, 0xe3, 0x03, 0x64, 0x4a, 0x5a, 0x05, 0x4b, 0x7e, 0x18, 0x91,
	0xe1, 0x71, 0xba, 0x0f, 0x3b, 0xeb, 0x31, 0x33, 0xe5, 0x8f, 0xd5, 0xdf, 0x59, 0x5b, 0xf8, 0x6d,
	0x85, 0xd1, 0x23, 0xb4, 0xda, 0x4c, 0xa5, 0xe2, 0x47, 0x61, 0xdf, 0x3e, 0x64, 0x31, 0x65, 0xce,
	0x63, 0x0d, 0x6a, 0x73, 0xe6, 0x08, 0xe7, 0xd6, 0xf3, 0x41, 0x50, 0xff, 0xa9, 0xdc, 0xdd, 0xbf,
	0x35, 0x82, 0xac, 0x1b, 0x41, 0x3e, 0x1a, 0x41, 0x5e, 0x5b, 0xd1, 0x5b, 0xb7, 0xa2, 0xf7, 0xde,
	0x8a, 0xde, 0xd3, 0xcd, 0xd4, 0xf8, 0x62, 0x3e, 0x89, 0x73, 0x9c, 0x25, 0xbb, 0xec, 0x92, 0x2e,
	0xe1, 0xe5, 0xf6, 0xe7, 0x57, 0x15, 0xb8, 0xc9, 0x20, 0xc4, 0x7c, 0xfb, 0x15, 0x00, 0x00, 0xff,
	0xff, 0x39, 0x9c, 0x46, 0xf4, 0x83, 0x01, 0x00, 0x00,
}

func (m *SystemInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SystemInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SystemInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.StoredSessionCount != 0 {
		i = encodeVarintSystemInfo(dAtA, i, uint64(m.StoredSessionCount))
		i--
		dAtA[i] = 0x30
	}
	if m.ChainConfigId != 0 {
		i = encodeVarintSystemInfo(dAtA, i, uint64(m.ChainConfigId))
		i--
		dAtA[i] = 0x28
	}
	if len(m.FifoTailIndex) > 0 {
		i -= len(m.FifoTailIndex)
		copy(dAtA[i:], m.FifoTailIndex)
		i = encodeVarintSystemInfo(dAtA, i, uint64(len(m.FifoTailIndex)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.FifoHeadIndex) > 0 {
		i -= len(m.FifoHeadIndex)
		copy(dAtA[i:], m.FifoHeadIndex)
		i = encodeVarintSystemInfo(dAtA, i, uint64(len(m.FifoHeadIndex)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ChainRoleId != 0 {
		i = encodeVarintSystemInfo(dAtA, i, uint64(m.ChainRoleId))
		i--
		dAtA[i] = 0x10
	}
	if m.ProofSessionId != 0 {
		i = encodeVarintSystemInfo(dAtA, i, uint64(m.ProofSessionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSystemInfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovSystemInfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SystemInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProofSessionId != 0 {
		n += 1 + sovSystemInfo(uint64(m.ProofSessionId))
	}
	if m.ChainRoleId != 0 {
		n += 1 + sovSystemInfo(uint64(m.ChainRoleId))
	}
	l = len(m.FifoHeadIndex)
	if l > 0 {
		n += 1 + l + sovSystemInfo(uint64(l))
	}
	l = len(m.FifoTailIndex)
	if l > 0 {
		n += 1 + l + sovSystemInfo(uint64(l))
	}
	if m.ChainConfigId != 0 {
		n += 1 + sovSystemInfo(uint64(m.ChainConfigId))
	}
	if m.StoredSessionCount != 0 {
		n += 1 + sovSystemInfo(uint64(m.StoredSessionCount))
	}
	return n
}

func sovSystemInfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSystemInfo(x uint64) (n int) {
	return sovSystemInfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SystemInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSystemInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SystemInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SystemInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofSessionId", wireType)
			}
			m.ProofSessionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSystemInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProofSessionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainRoleId", wireType)
			}
			m.ChainRoleId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSystemInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainRoleId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FifoHeadIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSystemInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSystemInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSystemInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FifoHeadIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FifoTailIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSystemInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSystemInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSystemInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FifoTailIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainConfigId", wireType)
			}
			m.ChainConfigId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSystemInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainConfigId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoredSessionCount", wireType)
			}
			m.StoredSessionCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSystemInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StoredSessionCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSystemInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSystemInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSystemInfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSystemInfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSystemInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSystemInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSystemInfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSystemInfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSystemInfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSystemInfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSystemInfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSystemInfo = fmt.Errorf("proto: unexpected end of group")
)
